db_clients:
  paper_docs_database:
    db_type: mongo
    db_name: paper_db
    dump_folder: query_dataset/paper_docs_dump

  citations_database:
    db_type: sqlite
    db_path: query_dataset/citations.db
