db_clients:
  metadata_dataset:
    db_type: sqlite
    db_path: query_dataset/repo_metadata.db
  artifacts_dataset:
    db_type: duckdb               # Database type: DuckDB
    db_path: query_dataset/repo_artifacts.db 


