db_clients:
  clinical_database:
    db_type: postgres
    db_name: pancancer_clinical
    sql_file: query_dataset/pancancer_clinical.sql

  molecular_database:
    db_type: duckdb               # Database type: DuckDB
    db_path: query_dataset/pancancer_molecular.db       # Path to the DuckDB file
