db_clients:
  articles_database:
    db_type: mongo                # Database type: MongoDB
    db_name: articles_db             # Name of the MongoDB database
    dump_folder: query_dataset/agnews_articles  # Folder with the MongoDB dump to initialize

  metadata_database:
    db_type: sqlite               # Database type: Sqlite
    db_path: query_dataset/metadata.db       # Path to the Sqlite file
