db_clients:
  publication_database:
    db_type: sqlite
    db_path: query_dataset/patent_publication.db
  CPCDefinition_database:
    db_type: postgres
    db_name: patent_CPCDefinition
    sql_file: query_dataset/patent_CPCDefinition.sql


