db_clients:
  publication_dataset:
    db_type: sqlite
    db_path: query_dataset/patent_publication.db
  CPCDefinition_dataset:
    db_type: postgres
    db_name: bookreview_db
    sql_file: query_dataset/books_info.sql


